# Generated by Django 3.2.13 on 2022-04-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSite', '0003_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='contain',
        ),
    ]
