# Generated by Django 3.2.13 on 2022-05-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSite', '0008_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
