# Generated by Django 3.2.13 on 2022-05-19 11:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_user_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hits', models.CharField(blank=True, max_length=255, null=True)),
                ('Passing_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Avg_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Score', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game_user',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='Full_name', unique=True),
        ),
    ]
