# Generated by Django 3.2.13 on 2022-05-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220519_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill_formula',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Drills-shape/'),
        ),
        migrations.AddField(
            model_name='score',
            name='AddPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.add_players'),
        ),
        migrations.AddField(
            model_name='score',
            name='Create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='score',
            name='GetDrill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.drill_data'),
        ),
        migrations.AddField(
            model_name='score',
            name='GetPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game_user'),
        ),
        migrations.AddField(
            model_name='score',
            name='Time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='Time_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
