# Generated by Django 3.2.13 on 2022-05-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20220520_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill_formula',
            name='image',
        ),
    ]
