# Generated by Django 3.2.13 on 2022-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20220525_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
