# Generated by Django 3.2.13 on 2022-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20220531_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='Avg_Time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scorebord',
            name='Avg_Time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
