# Generated by Django 3.2.13 on 2022-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20220531_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='Avg_Time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorebord',
            name='Avg_Time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
