# Generated by Django 3.2.13 on 2022-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_drill_formula_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill_formula',
            name='music',
            field=models.FileField(blank=True, default='Drills-Music/sound-effect.mp3', max_length=255, null=True, upload_to='Drills-Music/'),
        ),
    ]
