# Generated by Django 3.2.13 on 2022-06-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_drill_formula_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill_formula',
            name='music',
        ),
    ]
