# Generated by Django 3.2.13 on 2022-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_password_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_user',
            name='facebook_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game_user',
            name='google_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
