# Generated by Django 3.2.13 on 2022-07-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_contact_us_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
