# Generated by Django 3.2.13 on 2022-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_contact_us_contact_us_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_reply',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
