# Generated by Django 3.2.13 on 2022-07-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_contact_us_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_reply',
            name='GetMail',
        ),
        migrations.DeleteModel(
            name='Contact_Us',
        ),
        migrations.DeleteModel(
            name='Contact_Us_reply',
        ),
    ]
