# Generated by Django 3.2.13 on 2022-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_contact_us_contact_us_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='Today',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact_us_reply',
            name='Today',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
