# Generated by Django 3.2.13 on 2022-07-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20220711_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Token', models.TextField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Is_Active', models.CharField(choices=[('1', 'Active'), ('0', 'Deactive')], default='1', max_length=10)),
                ('Today', models.DateField(blank=True, max_length=255, null=True)),
                ('Create_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('GetUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game_user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Today', models.DateField(blank=True, max_length=255, null=True)),
                ('Create_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('GetMail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.contact_us')),
            ],
        ),
    ]
